FROM ubuntu:18.04
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip wget zlib1g-dev
WORKDIR /tmp
RUN wget https://github.com/git/git/archive/refs/tags/v1.8.3.zip
RUN unzip v1.8.3.zip && cd git-1.8.3 && make prefix=/usr/local all && make prefix=/usr/local install
RUN apt-get clean && rm -rf /tmp/*