FROM ubuntu:20.04
RUN export DEBIAN_FRONTEND=noninteractive && apt-get update && apt-get install -y build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip wget zlib1g-dev python3 python3-pip
RUN python3 -m pip install bce-python-sdk==0.8.74
WORKDIR /tmp
RUN wget https://github.com/git/git/archive/refs/tags/v2.34.0.zip
RUN unzip v2.34.0.zip && cd git-2.34.0 && make prefix=/usr/local all && make prefix=/usr/local install
RUN apt-get clean && rm -rf /tmp/*