FROM centos:7

# 更新镜像源为阿里云源
RUN yum install -y wget && \
    wget -O /etc/yum.repos.d/CentOS-Base.repo http://mirrors.aliyun.com/repo/Centos-7.repo && \
    yum clean all && \
    yum makecache

# 安装必要的依赖
RUN yum -y update && \
    yum -y groupinstall "Development Tools" && \
    yum -y install wget openssl-devel curl-devel expat-devel gettext-devel unzip perl-ExtUtils-MakeMaker zlib-devel

# 设置工作目录
WORKDIR /tmp

# 下载和编译 Git 1.8.3
RUN wget https://github.com/git/git/archive/refs/tags/v1.8.3.zip && \
    unzip v1.8.3.zip && \
    cd git-1.8.3 && \
    make prefix=/usr/local all && \
    make prefix=/usr/local install

# 清理临时文件
RUN yum clean all && rm -rf /tmp/*
