name: Docker Example Workflow

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a one-line command in the Docker container
      uses: docker://xieyunshen2020/paddleqa:code-clone-git2.34
      with:
        entrypoint: /bin/sh
        args: |
          -c "git --version;ls -lla"

    - name: Echo github context
      run: |
        echo "Base ref: ${{ github.base_ref }}"
        echo "Repository URL: ${{ github.repositoryUrl }}"
