name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  # check-bats-version:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'
  #     - run: npm install -g bats
  #     - run: bats -v
  #     - run: echo "my first GitHub Actions workflow"
  # llm-td_learning:
  #   name: before-test
  #   uses: ./.github/workflows/llm-td_learning.yml
  #   permissions:
  #     id-token: write
  #     contents: read
  test_bos:
    runs-on: ubuntu-latest
    steps:
      - name: Git Version
        run: git --version
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip

      - name: Download and install Git 2.34
        run: |
          wget https://github.com/git/git/archive/refs/tags/v2.34.0.zip
          unzip v2.34.0.zip
          cd git-2.34.0
          make prefix=/usr/local all
          sudo make prefix=/usr/local install

      - name: Check Git version
        run: git --version
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: paddletest-clone
        uses: actions/checkout@v4
        with:
          repository: paddlepaddle/PaddleTest
          path: PaddleTest
      - name: upload-source-code
        env: 
          AK: ${{ secrets.BOS_AK }}
          SK: ${{ secrets.BOS_SK }}
        run: |
          ls -l
          pwd
          tar -zcf PaddleTest.tar.gz PaddleTest
          python --version
          python -m pip install --upgrade pip
          python -m pip install bce-python-sdk==0.8.74
          python -m pip list
          echo ${BOS_AK}
          echo ${BOS_SK}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Branch Name: $BRANCH_NAME"
          python tools/bos_upload.py PaddleTest.tar.gz paddle-qa/CE-BuildTask-Clone/PaddleTestCodes/

