name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  test_bos:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-activate-base: true
          activate-environment: ""
      - name: paddletest-clone
        uses: actions/checkout@v4
        with:
          repository: paddlepaddle/PaddleTest
          path: PaddleTest
      - name: git-reinit
        run: |
          cd PaddleTest
          rm -rf .git
          git init
          git remote add origin https://github.com/paddlepaddle/PaddleTest.git
          git fetch origin develop
          git reset --hard origin/develop
      - name: upload-source-code
        env: 
          AK: ${{ secrets.BOS_AK }}
          SK: ${{ secrets.BOS_SK }}
        run: |
          ls -l
          pwd
          tar -zcf PaddleTest.tar.gz PaddleTest
          python --version
          python -m pip install --upgrade pip
          python -m pip install bce-python-sdk==0.8.74
          python -m pip list
          echo ${BOS_AK}
          echo ${BOS_SK}
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "Branch Name: $BRANCH_NAME"
          python tools/bos_upload.py PaddleTest.tar.gz paddle-qa/CE-BuildTask-Clone/PaddleTestCodes/

